/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import classes.Consulta;
import classes.Produto;
import classes.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import validacao.ValidaConsulta;

/**
 *
 * @author bp555787
 */
public class ConsultaProduto extends javax.swing.JFrame {

    public ConsultaProduto() {
        initComponents();
        /*
         Ao carregar a tela de consulta ja é verificado se o usuario tem
         Itens que estão embaixa no estoque
         */
        Consulta c = new Consulta();
        ArrayList produtosEmBaixaAlta = c.produtEmBaixaAlta();
        if (produtosEmBaixaAlta.size() > 0) {
            String[] colunas = {"CODIGO", "QUANTIDADE", "NOME", "QUANT MAX", " QUANT MIN"};
            c.setColunas(colunas);
            c.iniciarTabela(jTableConsulta, produtosEmBaixaAlta);
            jTableConsulta.setForeground(Color.red);
        }

    }

    /*metodo para fazer dados do usuário passar entre telas*/
    private Usuario user;

    public void setUsuario(Usuario a) {
        user = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsulta = new javax.swing.JTable();
        bntVoltar = new javax.swing.JButton();
        btnConsultaAll = new javax.swing.JButton();
        txtTarja = new javax.swing.JTextField();
        txtCodigo1 = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblLab = new javax.swing.JLabel();
        txtLab = new javax.swing.JTextField();
        lblTarja = new javax.swing.JLabel();
        lblEspecie = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        txtEspecie = new javax.swing.JTextField();
        btnConsultaCodigo = new javax.swing.JButton();
        btnConsultaHistorico = new javax.swing.JButton();
        txtTipoMedicamento = new javax.swing.JTextField();
        lblTipoMedicamento = new javax.swing.JLabel();
        btnConsultaNomes = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Código:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 30, 60, 30);

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodigo);
        txtCodigo.setBounds(80, 30, 80, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 30, 60, 30);

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });
        jPanel1.add(txtNome);
        txtNome.setBounds(230, 30, 340, 30);

        jTableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsulta);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 310, 550, 180);

        bntVoltar.setText("Voltar");
        bntVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(bntVoltar);
        bntVoltar.setBounds(20, 260, 80, 30);

        btnConsultaAll.setText("Consulta Completa");
        btnConsultaAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaAllActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultaAll);
        btnConsultaAll.setBounds(120, 260, 150, 30);

        txtTarja.setEditable(false);
        txtTarja.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtTarja);
        txtTarja.setBounds(310, 210, 110, 30);

        txtCodigo1.setEditable(false);
        txtCodigo1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtCodigo1);
        txtCodigo1.setBounds(90, 160, 110, 30);

        lblCodigo.setText("Codigo:");
        jPanel1.add(lblCodigo);
        lblCodigo.setBounds(30, 170, 44, 16);

        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblStatus.setText("Status:");
        jPanel1.add(lblStatus);
        lblStatus.setBounds(380, 100, 60, 30);

        lblLab.setText("laboratorio:");
        jPanel1.add(lblLab);
        lblLab.setBounds(10, 110, 80, 16);

        txtLab.setEditable(false);
        txtLab.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtLab);
        txtLab.setBounds(90, 100, 270, 30);

        lblTarja.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTarja.setText("Tarja:");
        jPanel1.add(lblTarja);
        lblTarja.setBounds(270, 210, 50, 30);

        lblEspecie.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEspecie.setText("Espécie :");
        jPanel1.add(lblEspecie);
        lblEspecie.setBounds(30, 210, 60, 30);

        txtStatus.setEditable(false);
        txtStatus.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtStatus);
        txtStatus.setBounds(430, 100, 140, 30);

        txtEspecie.setEditable(false);
        txtEspecie.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtEspecie);
        txtEspecie.setBounds(90, 210, 140, 30);

        btnConsultaCodigo.setText("Consultar Codigo");
        btnConsultaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaCodigoActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultaCodigo);
        btnConsultaCodigo.setBounds(290, 260, 130, 30);

        btnConsultaHistorico.setText("Hist. movimento");
        btnConsultaHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaHistoricoActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultaHistorico);
        btnConsultaHistorico.setBounds(440, 210, 130, 30);

        txtTipoMedicamento.setEditable(false);
        txtTipoMedicamento.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtTipoMedicamento);
        txtTipoMedicamento.setBounds(350, 160, 170, 30);

        lblTipoMedicamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTipoMedicamento.setText("Tipo do Produto:");
        jPanel1.add(lblTipoMedicamento);
        lblTipoMedicamento.setBounds(240, 160, 100, 30);

        btnConsultaNomes.setText("Consultar Nome");
        btnConsultaNomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaNomesActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultaNomes);
        btnConsultaNomes.setBounds(440, 260, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(592, 541));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void bntVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarActionPerformed
        Menu m = new Menu();
        //passando dados do usuário para outras telas
        user.setAviso(true);
        m.setUsuario(user);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bntVoltarActionPerformed

    private void jTableConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaMouseClicked
        Consulta c = new Consulta();
        Produto p = new Produto();

        //captura o quantidade de cliques
        if (evt.getClickCount() == 2) {
            int codigo = (int) (jTableConsulta.getModel().getValueAt(jTableConsulta.getSelectedRow(), 0));
            int tipoProduto = (int) jTableConsulta.getModel().getValueAt(jTableConsulta.getSelectedRow(), 4);
            /*
             pega o codigo do produto e consulta no banco suas informações 
             depedendo do tipo do produto e solicitado um metodo
             */
            if (tipoProduto == 1) {
                p = c.preencheMaterial(codigo);
            } else if (tipoProduto == 2) {
                p = c.preencheLimpeza(codigo);
            } else if (tipoProduto == 3) {
                p = c.preencheMedicamento(codigo);
            }
            /*
             seta os valores da consulta no campos
             */
            System.out.println(p.getTipoProduto());
            System.out.println(codigo + " " + tipoProduto);
            txtCodigo1.setText(String.valueOf(codigo));
            txtLab.setText(p.getLaboratorio());
            txtStatus.setText(p.getEstado());
            txtTarja.setText(p.getTarja());
            txtEspecie.setText(p.getTipoAnimal());
            txtTipoMedicamento.setText(c.TipoMedicamento(tipoProduto));

        }

    }//GEN-LAST:event_jTableConsultaMouseClicked

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        /*So aceita a entra de números*/
        String entrada = "0123456789";
        if (!entrada.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        /*so aceita um certo número de caracteres*/
        if (txtNome.getText().length() > 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNomeKeyTyped

    private void btnConsultaAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaAllActionPerformed

        Consulta consultCompleta = new Consulta();
        /*Consulta todos os dados do banco e ja seta na tebela padrao(CODIGO, NOME, QUANTIDA, PRODUTO, VALOR, TIPO)*/
        consultCompleta.iniciarTabelaPadrao(jTableConsulta, consultCompleta.consultarCompleta());
        jTableConsulta.setEnabled(true);//DEIXA AS INFORMAÇÕES E NÃO EDITAVEIS
        jTableConsulta.setForeground(Color.black);//DEIXAS A COR PRETA DOS DADOS DA TABELA
    }//GEN-LAST:event_btnConsultaAllActionPerformed

    private void btnConsultaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaCodigoActionPerformed
        ValidaConsulta c = new ValidaConsulta();
        /*Consulta Codigo e ja seta na tebela padrao(CODIGO, NOME, QUANTIDA, PRODUTO, VALOR, TIPO)*/
        //valida os dados da consulta
        if (c.validaCampos(txtCodigo.getText())) {

            Consulta consultCod = new Consulta();
            consultCod.iniciarTabelaPadrao(jTableConsulta, consultCod.consultarCodigo(Integer.parseInt(txtCodigo.getText())));
            jTableConsulta.setEnabled(true);
            jTableConsulta.setForeground(Color.black);
        } else {
            //mostra mensagem de validação
            c.msgmCodigo();
        }

    }//GEN-LAST:event_btnConsultaCodigoActionPerformed

    private void btnConsultaHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaHistoricoActionPerformed
        Consulta consultHistorico = new Consulta();
        /*Consulta historico e já seta na tebela com os nomes da coluna informados*/
        String[] colunas = {"FUNCIONARIO","COD", "PRODUTO", "QUANT", "DATA", "TIPO"};
        consultHistorico.setColunas(colunas);
        //aqui é passado a tabela eos dados da consulta
        consultHistorico.iniciarTabela(jTableConsulta, consultHistorico.consultarHistorico());
        jTableConsulta.setEnabled(false);
        jTableConsulta.setForeground(Color.black);
    }//GEN-LAST:event_btnConsultaHistoricoActionPerformed

    private void btnConsultaNomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaNomesActionPerformed
        ValidaConsulta c = new ValidaConsulta();

        //valida os dados da consulta
        if (c.validaCampos(txtNome.getText())) {
            Consulta consultNome = new Consulta();
            consultNome.iniciarTabelaPadrao(jTableConsulta, consultNome.consultarNome(txtNome.getText()));
            jTableConsulta.setEnabled(true);
            jTableConsulta.setForeground(Color.BLACK);
        } else {
            //mostra mensagem de validação
            c.msgmNome();
        }


    }//GEN-LAST:event_btnConsultaNomesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntVoltar;
    private javax.swing.JButton btnConsultaAll;
    private javax.swing.JButton btnConsultaCodigo;
    private javax.swing.JButton btnConsultaHistorico;
    private javax.swing.JButton btnConsultaNomes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEspecie;
    private javax.swing.JLabel lblLab;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTarja;
    private javax.swing.JLabel lblTipoMedicamento;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigo1;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtLab;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTarja;
    private javax.swing.JTextField txtTipoMedicamento;
    // End of variables declaration//GEN-END:variables
}
