/**
 * TADS 2º SEMESTRE PROJETO CLINICA VETERINARIA CONTROLE DE ESTOQUE
 * 
 * DATA: 11/01/2015
 * 
 * GRUPO: MIQUEAS, VICTOR E GUSTAVO.
 * 
 * PROFª: ALESSANDRA.
 * 
 * REPOSITORIO:
 * 
 */
package layout;

/**
 *
 * @author bp555787
 */
import classes.Usuario;
import java.util.Arrays;
import validacao.ValidaLogin;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("RecuperaCão");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 10, 150, 30);

        btnEntrar.setText("Ok");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar);
        btnEntrar.setBounds(100, 170, 90, 25);

        btnSair.setText("Cancelar");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair);
        btnSair.setBounds(210, 170, 90, 25);

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        jPanel1.add(txtLogin);
        txtLogin.setBounds(110, 90, 190, 30);
        jPanel1.add(txtSenha);
        txtSenha.setBounds(110, 130, 190, 30);

        jLabel2.setText("Clinica Veterinaria");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 40, 130, 16);

        lblLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLogin.setText("Login:");
        jPanel1.add(lblLogin);
        lblLogin.setBounds(60, 90, 60, 30);

        lblSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSenha.setText("Senha:");
        jPanel1.add(lblSenha);
        lblSenha.setBounds(60, 130, 60, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(366, 223));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        Usuario dadosUsuario = new Usuario();//intancia classe usuario
        ValidaLogin validarUsuario = new ValidaLogin();//instancia a classe validar, responsavel por exibir as mensagens na tela
        dadosUsuario.setUsurario(txtLogin.getText());//passando o nome do usuario
        dadosUsuario.setSenha(Arrays.toString(txtSenha.getPassword()).replaceAll(", ", ""));//passando a senha do usuario e convertendo-a para string, porque seu estado original é um tipo char[]
        dadosUsuario.setCodigo(dadosUsuario.codigoFunc(dadosUsuario));//aqui é validado no banco de dados se o usuário realmente existe
        dadosUsuario.setAviso(false);
        //System.out.println(txtLogin.getText());
        //System.out.println(validarUsuario.validaCampos(dadosUsuario));
        //System.out.println(Arrays.toString(txtSenha.getPassword()).replaceAll(", ", ""));
        
        //somente válida campos, caso esteja preenchido entra na condição
        if (validarUsuario.validaCampos(dadosUsuario)) {
            //se a função retornar 0 e porque não existe usuário
            if (dadosUsuario.getCodigo()!=0) {
                Menu m = new Menu();//instancia a classe formulario menu
               //m.avisarUser(dadosUsuario);//passa os valores do usuario para outras telas, assim podemos capturar sua atividade
                m.setUsuario(dadosUsuario);
                m.setVisible(true);//mostrando a menu
                this.dispose();//destruindo memoria da tela login
            } else {
                //somente mostra a mensagem que o usuario não foi encontrado
                validarUsuario.usuarioNaoEncont();
            }
        } else {
            //somente exibe a mensagem, caso não esteja preenchido corretamente
            validarUsuario.validaCampoMgsm(dadosUsuario);
        }

    }//GEN-LAST:event_btnEntrarActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
       
    }//GEN-LAST:event_txtLoginActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
