/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import classes.Consulta;
import classes.Usuario;
import java.util.ArrayList;

/**
 *
 * @author bp555787
 */
public final class Menu extends javax.swing.JFrame {

    

    private Usuario user;

    public void setUsuario(Usuario u) {
        this.user = u;
    }
    
    
 
    /**
     * Creates new form menu
     */
    public Menu() {
        
        initComponents();
        Consulta c = new Consulta();
        ArrayList produtosEmBaixaAlta = c.produtEmBaixaAlta();
        if (produtosEmBaixaAlta.size() > 0) {
            lblAviso.setText("<html><body>AVISO: existem Produtos em Baixa/Alta consulte Estoque ou <br> "
                    + "Saida de Produtos para visualiza-los</body></html>\"");
            
        }
    }
    
    

       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bntCadstrar = new javax.swing.JButton();
        btnOutProdutos = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        btnLogoff = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblClinica = new javax.swing.JLabel();
        lblAviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel1.setLayout(null);

        bntCadstrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bntCadstrar.setText("Registrar produtos/materiais");
        bntCadstrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadstrarActionPerformed(evt);
            }
        });
        jPanel1.add(bntCadstrar);
        bntCadstrar.setBounds(80, 120, 250, 50);

        btnOutProdutos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnOutProdutos.setText("Saida de produtos/materiais");
        btnOutProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutProdutosActionPerformed(evt);
            }
        });
        jPanel1.add(btnOutProdutos);
        btnOutProdutos.setBounds(80, 180, 250, 50);

        btnConsulta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnConsulta.setText("Consultar produtos/materiais");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsulta);
        btnConsulta.setBounds(80, 60, 250, 50);

        btnLogoff.setText("LOGOFF");
        btnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoffActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogoff);
        btnLogoff.setBounds(320, 290, 90, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("RecuperaCão");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 10, 150, 30);

        lblClinica.setText("Clinica Veterinaria");
        jPanel1.add(lblClinica);
        lblClinica.setBounds(210, 40, 130, 14);

        lblAviso.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(lblAviso);
        lblAviso.setBounds(20, 230, 390, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(428, 321));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOutProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutProdutosActionPerformed
        MovimentoProduto m = new MovimentoProduto();
        m.setUsuario(user);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOutProdutosActionPerformed

    private void bntCadstrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadstrarActionPerformed
        RegistrarProduto r = new RegistrarProduto();
        r.setUsuario(user);
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bntCadstrarActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        ConsultaProduto c = new ConsultaProduto();
        c.setUsuario(user);
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoffActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCadstrar;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnLogoff;
    private javax.swing.JButton btnOutProdutos;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblClinica;
    // End of variables declaration//GEN-END:variables
}
