/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import classes.Consulta;
import classes.Movimento;
import classes.Produto;
import classes.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import validacao.ValidaMovimentacao;

/**
 *
 * @author bp555787
 */
public class MovimentoProduto extends javax.swing.JFrame {

    /**
     * Creates new form remover
     */
    public MovimentoProduto() {
        initComponents();
        Consulta c = new Consulta();

        ArrayList produtosEmBaixaAlta = c.produtEmBaixaAlta();
        if (produtosEmBaixaAlta.size() > 0) {
            String[] colunas = {"CODIGO", "QUANTIDADE", "NOME", "QUANT MAX", " QUANT MIN"};
            c.setColunas(colunas);
            c.iniciarTabela(jTable1, produtosEmBaixaAlta);
            jTable1.setForeground(Color.red);
            jTable1.setEnabled(false);
        }
    }

    private Usuario user;

    public void setUsuario(Usuario a) {
        user = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuantidade = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jCombMaterial = new javax.swing.JComboBox();
        btnVoltar = new javax.swing.JButton();
        lblTipo = new javax.swing.JLabel();
        btnSaidaProduto = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        btnInserir = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        btnVerificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblStatusAtual = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jCombMaterialAtualizar = new javax.swing.JComboBox();
        lblMaterialAtualizar = new javax.swing.JLabel();
        btnAtualizarMaterial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        lblQuantidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblQuantidade.setText("Quantidade:");
        getContentPane().add(lblQuantidade);
        lblQuantidade.setBounds(30, 130, 67, 15);

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCodigo.setText("Código:");
        getContentPane().add(lblCodigo);
        lblCodigo.setBounds(30, 70, 41, 15);

        jCombMaterial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Material Clínico", "Material de Limpeza", "Medicação", " " }));
        jCombMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombMaterialActionPerformed(evt);
            }
        });
        getContentPane().add(jCombMaterial);
        jCombMaterial.setBounds(300, 90, 150, 27);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(20, 460, 100, 32);

        lblTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTipo.setText("Tipo:");
        getContentPane().add(lblTipo);
        lblTipo.setBounds(300, 70, 40, 15);

        btnSaidaProduto.setText("Saida");
        btnSaidaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaidaProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaidaProduto);
        btnSaidaProduto.setBounds(340, 190, 110, 32);

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNome.setText("Nome:");
        getContentPane().add(lblNome);
        lblNome.setBounds(30, 10, 36, 15);

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        getContentPane().add(btnInserir);
        btnInserir.setBounds(210, 190, 110, 32);
        getContentPane().add(txtNome);
        txtNome.setBounds(30, 30, 350, 27);

        txtStatus.setEditable(false);
        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });
        txtStatus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStatusKeyTyped(evt);
            }
        });
        getContentPane().add(txtStatus);
        txtStatus.setBounds(300, 150, 150, 27);
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(30, 90, 91, 27);

        btnVerificar.setText("Buscar Produtos");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerificar);
        btnVerificar.setBounds(30, 190, 150, 32);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 230, 420, 210);

        lblStatusAtual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblStatusAtual.setText("Status Atual:");
        getContentPane().add(lblStatusAtual);
        lblStatusAtual.setBounds(300, 130, 80, 15);

        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyTyped(evt);
            }
        });
        getContentPane().add(txtQuantidade);
        txtQuantidade.setBounds(30, 150, 119, 27);

        jCombMaterialAtualizar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "nenhum", "Esterializado", "Não Esterializado", " " }));
        jCombMaterialAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombMaterialAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jCombMaterialAtualizar);
        jCombMaterialAtualizar.setBounds(140, 90, 150, 27);

        lblMaterialAtualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaterialAtualizar.setText("Atualizar Status:");
        getContentPane().add(lblMaterialAtualizar);
        lblMaterialAtualizar.setBounds(140, 70, 120, 15);

        btnAtualizarMaterial.setText("Atualizar");
        btnAtualizarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarMaterialActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizarMaterial);
        btnAtualizarMaterial.setBounds(170, 150, 110, 30);

        setSize(new java.awt.Dimension(472, 511));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCombMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombMaterialActionPerformed
        if (jCombMaterial.getSelectedItem().equals("Material Clínico")) {
            lblMaterialAtualizar.setVisible(true);
            jCombMaterialAtualizar.setVisible(true);
            txtStatus.setVisible(true);
            lblStatusAtual.setVisible(true);
            btnAtualizarMaterial.setVisible(true);
        } else {
            lblMaterialAtualizar.setVisible(false);
            jCombMaterialAtualizar.setVisible(false);
            txtStatus.setVisible(false);
            lblStatusAtual.setVisible(false);
            btnAtualizarMaterial.setVisible(false);
        }
    }//GEN-LAST:event_jCombMaterialActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        Menu m = new Menu();
        m.setUsuario(user);
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSaidaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaidaProdutoActionPerformed
        ValidaMovimentacao m = new ValidaMovimentacao();
        Movimento movimentar = new Movimento();
        Consulta consultCompleta = new Consulta();

        movimentar.setCodigoFuncionario(user.getCodigo());
        System.out.println(user.getCodigo());
        movimentar.setCodigoProduto(Integer.parseInt(txtCodigo.getText()));
        movimentar.setTipoMovimento(2);//Saida
        movimentar.setQuantidadeMovimento(Integer.parseInt(txtQuantidade.getText()));

        if (m.validarCampo(txtQuantidade.getText(), txtCodigo.getText())) {
            movimentar.setCodigoFuncionario(user.getCodigo());
            System.out.println(user.getCodigo());
            movimentar.setCodigoProduto(Integer.parseInt(txtCodigo.getText()));
            movimentar.setTipoMovimento(2);//Saida
            movimentar.setQuantidadeMovimento(Integer.parseInt(txtQuantidade.getText()));
            System.out.println(jCombMaterialAtualizar.getSelectedItem() + "");

            movimentar.saida(movimentar.getQuantidadeMovimento(), movimentar.getCodigoProduto(), movimentar);
            consultCompleta.iniciarTabelaPadrao(jTable1, consultCompleta.consultarCodigo(movimentar.getCodigoProduto()));

            int quantMax = consultCompleta.quantMax(movimentar.getCodigoProduto());
            int quantMin = consultCompleta.quantMin(movimentar.getCodigoProduto());
            int quantidadeItem = consultCompleta.consultarQuantidadeItem(movimentar.getCodigoProduto());

            if (quantidadeItem > quantMax) {
                m.mostraMsgmAlta();
                jTable1.setForeground(Color.red);
                //System.out.println(consultCompleta.consultarQuantidadeItem(movimentar.getCodigoProduto()));
            } else if(quantidadeItem < quantMin){
                m.mostraMsgmBaixa();
                jTable1.setForeground(Color.red);
            } else {
                jTable1.setForeground(Color.BLACK);
                //System.out.println(consultCompleta.consultarQuantidadeItem(movimentar.getCodigoProduto()));
            }

        } else {
            m.mostrarMsgm(txtStatus.getText(), txtCodigo.getText());
        }

    }//GEN-LAST:event_btnSaidaProdutoActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        ValidaMovimentacao m = new ValidaMovimentacao();
        Movimento movimentar = new Movimento();
        Consulta consultCompleta = new Consulta();

        if (m.validarCampo(txtQuantidade.getText(), txtCodigo.getText())) {
            movimentar.setCodigoFuncionario(user.getCodigo());
            System.out.println(user.getCodigo());
            movimentar.setCodigoProduto(Integer.parseInt(txtCodigo.getText()));
            movimentar.setTipoMovimento(1);//Saida
            movimentar.setQuantidadeMovimento(Integer.parseInt(txtQuantidade.getText()));
            System.out.println(jCombMaterialAtualizar.getSelectedItem() + "");
            movimentar.entrada(movimentar.getQuantidadeMovimento(), movimentar.getCodigoProduto(), movimentar);
            consultCompleta.iniciarTabelaPadrao(jTable1, consultCompleta.consultarCodigo(movimentar.getCodigoProduto()));

            int quantMax = consultCompleta.quantMax(movimentar.getCodigoProduto());
            int quantMin = consultCompleta.quantMin(movimentar.getCodigoProduto());
            int quantidadeItem = consultCompleta.consultarQuantidadeItem(movimentar.getCodigoProduto());

            if (quantidadeItem > quantMax) {
                m.mostraMsgmAlta();
                jTable1.setForeground(Color.red);
                //System.out.println(consultCompleta.consultarQuantidadeItem(movimentar.getCodigoProduto()));
            } else if(quantidadeItem < quantMin){
                m.mostraMsgmBaixa();
                jTable1.setForeground(Color.red);
            } else {
                jTable1.setForeground(Color.BLACK);
                //System.out.println(consultCompleta.consultarQuantidadeItem(movimentar.getCodigoProduto()));
            }

        } else {
            m.mostrarMsgm(txtQuantidade.getText(), txtCodigo.getText());
        }

    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        Consulta consultCompleta = new Consulta();
        consultCompleta.iniciarTabelaPadrao(jTable1, consultCompleta.consultarTipoProduto(jCombMaterial.getSelectedIndex() + 1));
        jTable1.setForeground(Color.black);
        jTable1.setEnabled(true);

    }//GEN-LAST:event_btnVerificarActionPerformed

    private void txtStatusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStatusKeyTyped
        String soNumeros = "0123456789";
        if (!soNumeros.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtStatusKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        Produto p = new Produto();
        Consulta c = new Consulta();

        txtNome.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3) + "");
        txtQuantidade.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1) + "");
        txtCodigo.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0) + "");
        if (jCombMaterial.getSelectedItem().equals("Material Clínico")) {
            p = c.preencheMaterial(Integer.parseInt(txtCodigo.getText()));
            txtStatus.setText(p.getEstado());
        }
       

    }//GEN-LAST:event_jTable1MouseClicked

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeKeyTyped

    private void jCombMaterialAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombMaterialAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombMaterialAtualizarActionPerformed

    private void btnAtualizarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarMaterialActionPerformed
        ValidaMovimentacao m = new ValidaMovimentacao();
        Movimento movimentar = new Movimento();
        Consulta c = new Consulta();
        Produto p = new Produto();

        if (m.validarCampo(txtQuantidade.getText(), txtCodigo.getText())) {
            movimentar.setCodigoFuncionario(user.getCodigo());
            movimentar.setCodigoProduto(Integer.parseInt(txtCodigo.getText()));
            movimentar.setTipoMovimento(3);//Esterialização
            movimentar.setQuantidadeMovimento(Integer.parseInt(txtQuantidade.getText()));
            System.out.println(jCombMaterialAtualizar.getSelectedItem() + "");
            if (m.validaMaterial(jCombMaterialAtualizar.getSelectedItem() + "")) {
                if (c.consultarQuantidadeItem(movimentar.getCodigoProduto())!=0) {
                    movimentar.estrializarMaterial(Integer.parseInt(txtCodigo.getText()), jCombMaterialAtualizar.getSelectedItem() + "", movimentar);
                    p = c.preencheMaterial(Integer.parseInt(txtCodigo.getText()));
                    txtStatus.setText(p.getEstado());
                }else{
                    m.msgmAtulizarInvalida();
                }
            } else {
                m.mostrarMsgmMaterial();
            }

        } else {
            m.mostrarMsgm(txtQuantidade.getText(), txtCodigo.getText());
        }

    }//GEN-LAST:event_btnAtualizarMaterialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovimentoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovimentoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovimentoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovimentoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovimentoProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarMaterial;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSaidaProduto;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox jCombMaterial;
    private javax.swing.JComboBox jCombMaterialAtualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblMaterialAtualizar;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblStatusAtual;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
